
spring:
  application:
    name: muffin-vs-chihuahua-4j

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#org.springframework.cloud.bindings.boot.enable: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR    
    org.hibernate: ERROR
    org.springframework.cloud.bindings: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
    org.moussaud: debug
    ai.djl: debug
    