spring:
  application:
    name: muffin-vs-chihuahua-4j
  thymeleaf:
    cache: false # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#org.springframework.cloud.bindings.boot.enable: true

logging:
  level:
    org.moussaud: debug
    ai.djl: debug
